# .github/workflows/build.yml
name: Build Only

on:
  push:
    branches: [ feature/*, bugfix/*, experimental/* ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '9.0.x'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    name: Quick Build Validation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    
    - name: Restore dependencies
      run: dotnet restore --verbosity minimal
    
    - name: Build solution
      run: dotnet build --configuration Release --no-restore --verbosity minimal
    
    - name: Check for build warnings
      run: |
        echo "✅ Build completed successfully!"
        echo "Branch: ${{ github.ref_name }}"
        echo "Commit: ${{ github.sha }}"
    
    - name: Quick smoke test
      run: |
        echo "Running quick validation..."
        dotnet build --configuration Debug --no-restore --verbosity minimal
        echo "✅ Debug build also successful!"